version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - checkout
      - setup_remote_docker

      - run:
          command: pip install -r requirements.txt
          name: Install dependencies

      - run:
          command: setsid python -m SimpleHTTPServer 8080
          pwd: /gordon-test/server-root
          background: true

      - run:
          name: make some files
          command: |
            mkdir -p /tmp/my_artifacts
            echo "first artifact" > /tmp/my_artifacts/first
            echo "second artifact" > /tmp/my_artifacts/second

      - store_artifacts:
          path: /tmp/my_artifacts
          destination: text-data
  test:
    machine: true
    steps:
      - run: date

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying!"
          pwd: /

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: /m.ster/
          requires:
            - build
            - test
